adds task 6
senachary/be-nc-news pull request #5
Opened 2023-08-15 14:45 UTC by senachary

2023-08-16 10:41 UTC, 2202Hannah requested changes
Hi Sen, there are some additional considerations to be made for this ticket. Please see my in line comments and update your code. Please submit another pull request when you are ready and make sure you have removed .only from your tests.

2023-08-16 10:41 UTC, 2202Hannah commented on __tests__/app.test.js
> +describe.only("GET /api/articles/:article_id/comments", () => {
Remove .only from your tests please

2023-08-16 10:41 UTC, 2202Hannah commented on __tests__/app.test.js
> +    })
Please consider the following tests for errors:
> the article_id is invalid e.g. 'not-an-id'
> the article_id is not present in the database e.g. 9999

2023-08-16 10:41 UTC, 2202Hannah commented on __tests__/app.test.js
> +            })
Please add a test where the article_id exists but there are no comments for that article

2023-08-18 08:47 UTC, B7Bprog requested changes
Hey Sen, please see my comments and refactor your code, then please send us a PR with it.

2023-08-18 08:47 UTC, B7Bprog commented on __tests__/app.test.js
> +        });
We want to make sure that we get all the comments back. Please write a test where you check the length of the array and iterate through it and check each comment for those properties.

2023-08-18 08:47 UTC, B7Bprog commented on __tests__/app.test.js
> +            })
Please add another test where there are no comments for an article, but the request is successful and returning an empty array of comments.

2023-08-18 08:47 UTC, B7Bprog commented on controllers/comments-controller.js
> +            if (comments.length === 0) {
Error responses should be handled in your error handling middleware in app.js.

2023-08-18 08:47 UTC, B7Bprog commented on controllers/comments-controller.js
> +    const article_id = req.params.article_id;
You will need to check the reason for the query returning empty rows:
- article exists but has no comments.
- article does not exist.
You will need to check whether the article exists in order to determine this.
I recommend the use of Promise.all() here for efficiency.

2023-08-18 08:47 UTC, B7Bprog commented on __tests__/app.test.js
> +        test("Should return 404: the article_id exists but there are no comments for that article", () => {
This should be 200. Please see my comment above recommending this test.

2023-09-05 09:55 UTC, merged